### PR TITLE
Add test to choose the good phpunit version

### PR DESCRIPTION
**Pull request by TOTOleHero**

### CODE REVIEW

**Comment by TOTOleHero** [comment]
I don't know how to fix indepotence pb ?

**Comment by oktapodia** [comment]
Thanks for your pull request!

To fix the Idempotence test you must not have any `changed` when the ansible running again, it's looks like you extract php version anytime

You should use the `when` to avoid that. [eg](https://github.com/oktapodia/ansible-role-phpunit/blob/master/tasks/main.yml#L5)

**Comment by thiagogomesverissimo** [comment]
In my option, a better approach is to leave the phpunit url as an ansible variable, so it can be set in playbook.

**Comment by oktapodia** [comment]
Agree with @thiagogomesverissimo that will avoid some future changing from the PHPUnit website

**Pull request closed without merging**
