### PR TITLE
url phpunit as ansible variable

### LINKED ISSUE #4: Implements phpunit url as ansible variable

### PR DESCRIPTION
**Pull request by thiagogomesverissimo**
Fix #4 :wolf:

### CODE REVIEW

**Comment by thiagogomesverissimo** [comment]
The geerlingguy.php role is failing at your travis-ci test...

**Comment by oktapodia** [comment]
Yes looks like something needs to be updated, I created an issue about and I will try to resolve it when I'll have time https://github.com/oktapodia/ansible-role-phpunit/issues/6

**Comment by thiagogomesverissimo** [comment]
Given this PR change only two lines, it could be merged before fix travis problem, not?

**Comment by oktapodia** [comment]
@thiagogomesverissimo I fixed the tests, please rebase

**Comment by thiagogomesverissimo** [comment]
done

**Comment by oktapodia** [comment]
Merged! Thank you for your contribution

**Pull request merged**
